modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="precast_structure"
version="${version}"
displayName="Pre-cast Structure"
authors="oOBoomberOo"
description='''
Scan framed builds into blueprints, print them into pre-cast structure items, and place the structure with a hologram deploy preview.
'''
displayURL="https://github.com/oOBoomberOo/precast-structure"
logoFile="assets/precast_structure/icon.png"
logoBlur=false

[[dependencies.precast_structure]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.precast_structure]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.precast_structure]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="AFTER"
side="BOTH"

[[dependencies.precast_structure]]
modId="cloth_config"
mandatory=true
versionRange="[11,)"
ordering="NONE"
side="CLIENT"
