modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="precast_structure"
version="${version}"
displayName="Pre-cast Structure"
authors="oOBoomberOo"
description='''
Scan framed builds into blueprints, print them into pre-cast structure items, and place the structure with a hologram deploy preview.
'''
displayURL="https://github.com/oOBoomberOo/precast-structure"
logoFile="assets/precast_structure/icon.png"
logoBlur=false

[[dependencies.precast_structure]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.precast_structure]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.precast_structure]]
modId="architectury"
type="required"
versionRange="[13.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.precast_structure]]
modId="cloth_config"
type="required"
versionRange="[15,)"
ordering="NONE"
side="CLIENT"
